name: benchmark
description: GitHub action to run benchmark using the luau execution api
author: nightcycle

inputs:
  universe-id:
    description: The ID of the Roblox universe to run the benchmark in.
    default: "9690745121"
  place-id:
    description: The ID of the place to run the benchmark in.
    default: "111123068113322"
  rbx-api-key:
    description: The  API key to authenticate with the Roblox API.
    required: true
  data-release-version:
    description: the version of the data being uploaded
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Remove file-util line from rokit.toml
      shell: bash
      run: |
        sed -i '/file-util/d' rokit.toml

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2
      with:
        cache: true

    - name: Install jq
      uses: dcarbone/install-jq-action@v2.1.0
      with:
        version: 'latest'

    - name: Run shell script
      shell: bash
      run: |
        export RBX_API_KEY=${{ inputs.rbx-api-key }}
        sh scripts/workflow/benchmark/all.sh ${{ inputs.data-release-version }}