name: benchmark
description: GitHub action to run benchmark using the luau execution api
author: nightcycle

inputs:
  universe-id:
    description: The ID of the Roblox universe to run the benchmark in.
    default: "9690745121"
  place-id:
    description: The ID of the place to run the benchmark in.
    default: "111123068113322"
  rbx-api-key:
    description: The  API key to authenticate with the Roblox API.
    required: true
  data-release-version:
    description: the version of the data being uploaded
    required: true
  data-update-token:
    description: the token used to update the data submodule with the new benchmark results
    required: true
  data-submodule-path:
    description: the path to the data submodule relative to the root of the repository
    required: true
  data-dir-path:
    description: the path within the data submodule to upload the benchmark results to
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true
        token: ${{ inputs.data-update-token }}

    - name: Remove file-util line from rokit.toml
      shell: bash
      run: |
        sed -i '/file-util/d' rokit.toml

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2
      with:
        cache: true

    - name: Install jq
      uses: dcarbone/install-jq-action@v2.1.0
      with:
        version: 'latest'

    - name: Configure git credentials
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global url."https://x-access-token:${{ inputs.data-update-token }}@github.com/".insteadOf "https://github.com/"

    - name: Run shell script
      shell: bash
      run: |
        export RBX_API_KEY=${{ inputs.rbx-api-key }}
        export DATA_SUBMODULE_PATH=${{ inputs.data-submodule-path }}
        export DATA_DIR_PATH=${{ inputs.data-dir-path }}
        export GH_TOKEN=${{ inputs.data-update-token }}
        sh scripts/workflow/benchmark/all.sh ${{ inputs.data-release-version }}